// Canonical Surah name table (English + Arabic), keyed by surah number 1–114.
// Extracted from the original seed's surahData so the structure generator and any
// other tooling share a single source of truth for names. Page/structure data no
// longer lives here — it comes from data/quranStructure.json.

const SURAH_NAMES = [
  { number: 1, name: 'Al-Fatiha', nameArabic: 'الفاتحة' },
  { number: 2, name: 'Al-Baqarah', nameArabic: 'البقرة' },
  { number: 3, name: 'Aal-Imran', nameArabic: 'آل عمران' },
  { number: 4, name: 'An-Nisa', nameArabic: 'النساء' },
  { number: 5, name: "Al-Ma'idah", nameArabic: 'المائدة' },
  { number: 6, name: "Al-An'am", nameArabic: 'الأنعام' },
  { number: 7, name: "Al-A'raf", nameArabic: 'الأعراف' },
  { number: 8, name: 'Al-Anfal', nameArabic: 'الأنفال' },
  { number: 9, name: 'At-Tawbah', nameArabic: 'التوبة' },
  { number: 10, name: 'Yunus', nameArabic: 'يونس' },
  { number: 11, name: 'Hud', nameArabic: 'هود' },
  { number: 12, name: 'Yusuf', nameArabic: 'يوسف' },
  { number: 13, name: "Ar-Ra'd", nameArabic: 'الرعد' },
  { number: 14, name: 'Ibrahim', nameArabic: 'إبراهيم' },
  { number: 15, name: 'Al-Hijr', nameArabic: 'الحجر' },
  { number: 16, name: 'An-Nahl', nameArabic: 'النحل' },
  { number: 17, name: 'Al-Isra', nameArabic: 'الإسراء' },
  { number: 18, name: 'Al-Kahf', nameArabic: 'الكهف' },
  { number: 19, name: 'Maryam', nameArabic: 'مريم' },
  { number: 20, name: 'Ta-Ha', nameArabic: 'طه' },
  { number: 21, name: 'Al-Anbiya', nameArabic: 'الأنبياء' },
  { number: 22, name: 'Al-Hajj', nameArabic: 'الحج' },
  { number: 23, name: "Al-Mu'minun", nameArabic: 'المؤمنون' },
  { number: 24, name: 'An-Nur', nameArabic: 'النور' },
  { number: 25, name: 'Al-Furqan', nameArabic: 'الفرقان' },
  { number: 26, name: "Ash-Shu'ara", nameArabic: 'الشعراء' },
  { number: 27, name: 'An-Naml', nameArabic: 'النمل' },
  { number: 28, name: 'Al-Qasas', nameArabic: 'القصص' },
  { number: 29, name: 'Al-Ankabut', nameArabic: 'العنكبوت' },
  { number: 30, name: 'Ar-Rum', nameArabic: 'الروم' },
  { number: 31, name: 'Luqman', nameArabic: 'لقمان' },
  { number: 32, name: 'As-Sajdah', nameArabic: 'السجدة' },
  { number: 33, name: 'Al-Ahzab', nameArabic: 'الأحزاب' },
  { number: 34, name: 'Saba', nameArabic: 'سبأ' },
  { number: 35, name: 'Fatir', nameArabic: 'فاطر' },
  { number: 36, name: 'Ya-Sin', nameArabic: 'يس' },
  { number: 37, name: 'As-Saffat', nameArabic: 'الصافات' },
  { number: 38, name: 'Sad', nameArabic: 'ص' },
  { number: 39, name: 'Az-Zumar', nameArabic: 'الزمر' },
  { number: 40, name: 'Ghafir', nameArabic: 'غافر' },
  { number: 41, name: 'Fussilat', nameArabic: 'فصلت' },
  { number: 42, name: 'Ash-Shura', nameArabic: 'الشورى' },
  { number: 43, name: 'Az-Zukhruf', nameArabic: 'الزخرف' },
  { number: 44, name: 'Ad-Dukhan', nameArabic: 'الدخان' },
  { number: 45, name: 'Al-Jathiyah', nameArabic: 'الجاثية' },
  { number: 46, name: 'Al-Ahqaf', nameArabic: 'الأحقاف' },
  { number: 47, name: 'Muhammad', nameArabic: 'محمد' },
  { number: 48, name: 'Al-Fath', nameArabic: 'الفتح' },
  { number: 49, name: 'Al-Hujurat', nameArabic: 'الحجرات' },
  { number: 50, name: 'Qaf', nameArabic: 'ق' },
  { number: 51, name: 'Adh-Dhariyat', nameArabic: 'الذاريات' },
  { number: 52, name: 'At-Tur', nameArabic: 'الطور' },
  { number: 53, name: 'An-Najm', nameArabic: 'النجم' },
  { number: 54, name: 'Al-Qamar', nameArabic: 'القمر' },
  { number: 55, name: 'Ar-Rahman', nameArabic: 'الرحمن' },
  { number: 56, name: "Al-Waqi'ah", nameArabic: 'الواقعة' },
  { number: 57, name: 'Al-Hadid', nameArabic: 'الحديد' },
  { number: 58, name: 'Al-Mujadila', nameArabic: 'المجادلة' },
  { number: 59, name: 'Al-Hashr', nameArabic: 'الحشر' },
  { number: 60, name: 'Al-Mumtahanah', nameArabic: 'الممتحنة' },
  { number: 61, name: 'As-Saff', nameArabic: 'الصف' },
  { number: 62, name: "Al-Jumu'ah", nameArabic: 'الجمعة' },
  { number: 63, name: 'Al-Munafiqun', nameArabic: 'المنافقون' },
  { number: 64, name: 'At-Taghabun', nameArabic: 'التغابن' },
  { number: 65, name: 'At-Talaq', nameArabic: 'الطلاق' },
  { number: 66, name: 'At-Tahrim', nameArabic: 'التحريم' },
  { number: 67, name: 'Al-Mulk', nameArabic: 'الملك' },
  { number: 68, name: 'Al-Qalam', nameArabic: 'القلم' },
  { number: 69, name: 'Al-Haqqah', nameArabic: 'الحاقة' },
  { number: 70, name: "Al-Ma'arij", nameArabic: 'المعارج' },
  { number: 71, name: 'Nuh', nameArabic: 'نوح' },
  { number: 72, name: 'Al-Jinn', nameArabic: 'الجن' },
  { number: 73, name: 'Al-Muzzammil', nameArabic: 'المزمل' },
  { number: 74, name: 'Al-Muddaththir', nameArabic: 'المدثر' },
  { number: 75, name: 'Al-Qiyamah', nameArabic: 'القيامة' },
  { number: 76, name: 'Al-Insan', nameArabic: 'الإنسان' },
  { number: 77, name: 'Al-Mursalat', nameArabic: 'المرسلات' },
  { number: 78, name: 'An-Naba', nameArabic: 'النبأ' },
  { number: 79, name: "An-Nazi'at", nameArabic: 'النازعات' },
  { number: 80, name: 'Abasa', nameArabic: 'عبس' },
  { number: 81, name: 'At-Takwir', nameArabic: 'التكوير' },
  { number: 82, name: 'Al-Infitar', nameArabic: 'الانفطار' },
  { number: 83, name: 'Al-Mutaffifin', nameArabic: 'المطففين' },
  { number: 84, name: 'Al-Inshiqaq', nameArabic: 'الانشقاق' },
  { number: 85, name: 'Al-Buruj', nameArabic: 'البروج' },
  { number: 86, name: 'At-Tariq', nameArabic: 'الطارق' },
  { number: 87, name: "Al-A'la", nameArabic: 'الأعلى' },
  { number: 88, name: 'Al-Ghashiyah', nameArabic: 'الغاشية' },
  { number: 89, name: 'Al-Fajr', nameArabic: 'الفجر' },
  { number: 90, name: 'Al-Balad', nameArabic: 'البلد' },
  { number: 91, name: 'Ash-Shams', nameArabic: 'الشمس' },
  { number: 92, name: 'Al-Layl', nameArabic: 'الليل' },
  { number: 93, name: 'Ad-Duha', nameArabic: 'الضحى' },
  { number: 94, name: 'Ash-Sharh', nameArabic: 'الشرح' },
  { number: 95, name: 'At-Tin', nameArabic: 'التين' },
  { number: 96, name: 'Al-Alaq', nameArabic: 'العلق' },
  { number: 97, name: 'Al-Qadr', nameArabic: 'القدر' },
  { number: 98, name: 'Al-Bayyinah', nameArabic: 'البينة' },
  { number: 99, name: 'Az-Zalzalah', nameArabic: 'الزلزلة' },
  { number: 100, name: 'Al-Adiyat', nameArabic: 'العاديات' },
  { number: 101, name: "Al-Qari'ah", nameArabic: 'القارعة' },
  { number: 102, name: 'At-Takathur', nameArabic: 'التكاثر' },
  { number: 103, name: 'Al-Asr', nameArabic: 'العصر' },
  { number: 104, name: 'Al-Humazah', nameArabic: 'الهمزة' },
  { number: 105, name: 'Al-Fil', nameArabic: 'الفيل' },
  { number: 106, name: 'Quraysh', nameArabic: 'قريش' },
  { number: 107, name: "Al-Ma'un", nameArabic: 'الماعون' },
  { number: 108, name: 'Al-Kawthar', nameArabic: 'الكوثر' },
  { number: 109, name: 'Al-Kafirun', nameArabic: 'الكافرون' },
  { number: 110, name: 'An-Nasr', nameArabic: 'النصر' },
  { number: 111, name: 'Al-Masad', nameArabic: 'المسد' },
  { number: 112, name: 'Al-Ikhlas', nameArabic: 'الإخلاص' },
  { number: 113, name: 'Al-Falaq', nameArabic: 'الفلق' },
  { number: 114, name: 'An-Nas', nameArabic: 'الناس' },
];

const SURAH_NAME_BY_NUMBER = Object.fromEntries(SURAH_NAMES.map(s => [s.number, s]));

module.exports = { SURAH_NAMES, SURAH_NAME_BY_NUMBER };
